### ISSUE TITLE
simple_alu.py - RuntimeError: BoolectorSolver::make_sort

### ISSUE THREAD

**Issue by 4ong** [upscale-project/pono#79]
How can I try to fix this?
Fresh build of pono with everything except CoreIR. 
--with-msat:
```
Traceback (most recent call last):
  File "/home/xxx/xxx/xxx/pono/examples/python-api/simple_alu.py", line 158, in <module>
    k_induction_attempt()
  File "/home/xxx/xxx/xxx/pono/examples/python-api/simple_alu.py", line 61, in k_induction_attempt
    prop = build_simple_alu_fts(s)
  File "/home/xxx/job/xxx/pono/examples/python-api/simple_alu.py", line 16, in build_simple_alu_fts
    fts = pono.FunctionalTransitionSystem(s)
  File "pono_imp.pxi", line 57, in pono.__AbstractTransitionSystem.__cinit__
RuntimeError: BoolectorSolver::make_sort

Process finished with exit code 1

```

Without msat:
```	
============== Running k-induction ==============
INIT
	(bvand (bvnot cfg) (ite (= spec_res imp_res) #b1 #b0))
TRANS
	(and (= spec_res.next (bvadd a b)) (= cfg cfg.next) (= imp_res.next (bvadd a (ite (= #b1 cfg) (bvadd (bvnot b) #b00000001) b))))
PROP
	(= spec_res imp_res)
None
KInduction returned unknown
Traceback (most recent call last):
  File "/home/xxx/pono/examples/python-api/simple_alu.py", line 159, in <module>
    interpolant_attempt()
  File "/home/xxx/pono/examples/python-api/simple_alu.py", line 82, in interpolant_attempt
    s = ss.create_msat_solver(False)
AttributeError: module 'smt_switch' has no attribute 'create_msat_solver'

Process finished with exit code 1
```

**Comment by makaimann** [comment]
Hmm.. just ran it locally and I can't reproduce this issue. Which python version are you using? I would recommend a python3 virtual environment.

Could you run the python tests? After building smt-switch with the python bindings flag, and building pono with `./configure.sh --with-msat --python`. Then build and run: `pip install -e ./build/python`. Then install `pytest` (`pip install pytest` and from the top level repository run `pytest ./tests`

**Comment by 4ong** [comment]
Thanks @makaimann 
Seems to be solved - after recreation of the python environment from the scrath.

**Comment by makaimann** [comment]
I'm glad it's resolved! I see issues like that with python environments sometimes -- haven't yet figured out what goes wrong.
